from django.db import models
from django.contrib.auth.models import User
# Create your models here.


class Student(models.Model):
    user=models.OneToOneField(User,on_delete=models.CASCADE,null=True)
    profile_pic= models.ImageField(upload_to='profile_pic/CustomerProfilePic/',null=True,blank=True)
    address = models.CharField(max_length=40)
    mobile = models.CharField(max_length=20,null=False)
    status=models.BooleanField(default=False)

    TYPE_SELECT = [
        ('0', 'Female'),
        ('1', 'male'),
    ]
    gender = models.CharField(max_length=11, default=0,choices=TYPE_SELECT)


    @property
    def get_name(self):
        return self.user.first_name + " " + self.user.last_name

    @property
    def get_instance(self):
        return self

    def __str__(self):
        return self.user.first_name


class med(models.Model):
    user=models.OneToOneField(User,on_delete=models.CASCADE,null=True)
    m = models.CharField(max_length=20,null=True)
    mobile=models.CharField(max_length=20,null=False)


class depinformation(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE,null=True)
    name=models.CharField(max_length=200,null=True)
    studentid=models.CharField(max_length=200,null=True)
    year=models.CharField(max_length=200,null=True)
    semester=models.CharField(max_length=200,null=True)
    department=models.CharField(max_length=200,null=True)
    subject=models.CharField(max_length=200,null=True)
    mark=models.CharField(max_length=200,null=True)

class tableinfo(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    registernumber=models.CharField(max_length=200,null=True)
    semester=models.IntegerField(max_length=200,null=True)
    department = models.CharField(max_length=200, null=True)
    attendance=models.CharField(max_length=200,null=True)
    assignment=models.CharField(max_length=200,null=True)
    seminar=models.CharField(max_length=200,null=True)
    total=models.IntegerField(max_length=200,null=True)



    ################################### attendance ##############

class SEM1(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    branch=models.CharField(max_length=200, null=True)
    sem = models.CharField(max_length=200, null=True)
    m1 = models.IntegerField(max_length=20, null=True)
    m2 = models.IntegerField(max_length=20, null=True)
    m3 = models.IntegerField(max_length=20, null=True)
    m4 = models.IntegerField(max_length=20, null=True)
    m5 = models.IntegerField(max_length=20, null=True)


class SEM2(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    branch = models.CharField(max_length=200, null=True)
    sem = models.CharField(max_length=200, null=True)
    m1 = models.IntegerField(max_length=20, null=True)
    m2 = models.IntegerField(max_length=20, null=True)
    m3 = models.IntegerField(max_length=20, null=True)
    m4 = models.IntegerField(max_length=20, null=True)
    m5 = models.IntegerField(max_length=20, null=True)


class SEM3(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    branch = models.CharField(max_length=200, null=True)
    sem = models.CharField(max_length=200, null=True)
    m1 = models.IntegerField(max_length=20, null=True)
    m2 = models.IntegerField(max_length=20, null=True)
    m3 = models.IntegerField(max_length=20, null=True)
    m4 = models.IntegerField(max_length=20, null=True)
    m5 = models.IntegerField(max_length=20, null=True)


class SEM4(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    branch = models.CharField(max_length=200, null=True)
    sem = models.CharField(max_length=200, null=True)
    m1 = models.IntegerField(max_length=20, null=True)
    m2 = models.IntegerField(max_length=20, null=True)
    m3 = models.IntegerField(max_length=20, null=True)
    m4 = models.IntegerField(max_length=20, null=True)
    m5 = models.IntegerField(max_length=20, null=True)

class SEM5(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    branch = models.CharField(max_length=200, null=True)
    sem = models.CharField(max_length=200, null=True)
    m1 = models.IntegerField(max_length=20, null=True)
    m2 = models.IntegerField(max_length=20, null=True)
    m3 = models.IntegerField(max_length=20, null=True)
    m4 = models.IntegerField(max_length=20, null=True)
    m5 = models.IntegerField(max_length=20, null=True)

class SEM6(models.Model):
    user=models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    branch = models.CharField(max_length=200, null=True)
    sem = models.CharField(max_length=200, null=True)
    m1 = models.IntegerField(max_length=20, null=True)
    m2 = models.IntegerField(max_length=20, null=True)
    m3 = models.IntegerField(max_length=20, null=True)
    m4 = models.IntegerField(max_length=20, null=True)
    m5 = models.IntegerField(max_length=20, null=True)







#--------------------------------------------subject models------------------------------------#



class TRANSACTIONS(models.Model):
    registernumber=models.CharField(max_length=200,null=True)
    nameofstudent=models.CharField(max_length=200,null=True)
    attendance=models.CharField(max_length=200,null=True)
    assignment=models.CharField(max_length=200,null=True)
    seminar=models.CharField(max_length=200,null=True)
    test1=models.CharField(max_length=200,null=True)
    test2=models.CharField(max_length=200,null=True)
    total=models.CharField(max_length=200,null=True)

class WAYS_WITH_WORDS(models.Model):
    registernumber=models.CharField(max_length=200,null=True)
    nameofstudent=models.CharField(max_length=200,null=True)
    attendance=models.CharField(max_length=200,null=True)
    assignment=models.CharField(max_length=200,null=True)
    seminar=models.CharField(max_length=200,null=True)
    test1=models.CharField(max_length=200,null=True)
    test2=models.CharField(max_length=200,null=True)
    total=models.CharField(max_length=200,null=True)

class COMPUTER_FUNDAMENTALS(models.Model):
    registernumber=models.CharField(max_length=200,null=True)
    nameofstudent=models.CharField(max_length=200,null=True)
    attendance=models.CharField(max_length=200,null=True)
    assignment=models.CharField(max_length=200,null=True)
    seminar=models.CharField(max_length=200,null=True)
    test1=models.CharField(max_length=200,null=True)
    test2=models.CharField(max_length=200,null=True)
    total=models.CharField(max_length=200,null=True)
class MATHS(models.Model):
    registernumber=models.CharField(max_length=200,null=True)
    nameofstudent=models.CharField(max_length=200,null=True)
    attendance=models.CharField(max_length=200,null=True)
    assignment=models.CharField(max_length=200,null=True)
    seminar=models.CharField(max_length=200,null=True)
    test1=models.CharField(max_length=200,null=True)
    test2=models.CharField(max_length=200,null=True)
    total=models.CharField(max_length=200,null=True)
class ELECTRONICS(models.Model):
    registernumber=models.CharField(max_length=200,null=True)
    nameofstudent=models.CharField(max_length=200,null=True)
    attendance=models.CharField(max_length=200,null=True)
    assignment=models.CharField(max_length=200,null=True)
    seminar=models.CharField(max_length=200,null=True)
    test1=models.CharField(max_length=200,null=True)
    test2=models.CharField(max_length=200,null=True)
    total=models.CharField(max_length=200,null=True)
class MALAYALAM(models.Model):
    registernumber=models.CharField(max_length=200,null=True)
    nameofstudent=models.CharField(max_length=200,null=True)
    attendance=models.CharField(max_length=200,null=True)
    assignment=models.CharField(max_length=200,null=True)
    seminar=models.CharField(max_length=200,null=True)
    test1=models.CharField(max_length=200,null=True)
    test2=models.CharField(max_length=200,null=True)
    total=models.CharField(max_length=200,null=True)
class HINDI(models.Model):
    registernumber=models.CharField(max_length=200,null=True)
    nameofstudent=models.CharField(max_length=200,null=True)
    attendance=models.CharField(max_length=200,null=True)
    assignment=models.CharField(max_length=200,null=True)
    seminar=models.CharField(max_length=200,null=True)
    test1=models.CharField(max_length=200,null=True)
    test2=models.CharField(max_length=200,null=True)
    total=models.CharField(max_length=200,null=True)
class ARABIC(models.Model):
    registernumber=models.CharField(max_length=200,null=True)
    nameofstudent=models.CharField(max_length=200,null=True)
    attendance=models.CharField(max_length=200,null=True)
    assignment=models.CharField(max_length=200,null=True)
    seminar=models.CharField(max_length=200,null=True)
    test1=models.CharField(max_length=200,null=True)
    test2=models.CharField(max_length=200,null=True)
    total=models.CharField(max_length=200,null=True)
class ZEITGEIST(models.Model):
    registernumber=models.CharField(max_length=200,null=True)
    nameofstudent=models.CharField(max_length=200,null=True)
    attendance=models.CharField(max_length=200,null=True)
    assignment=models.CharField(max_length=200,null=True)
    seminar=models.CharField(max_length=200,null=True)
    test1=models.CharField(max_length=200,null=True)
    test2=models.CharField(max_length=200,null=True)
    total=models.CharField(max_length=200,null=True)
class ACADEMIC_AND_PROFFESIONAL(models.Model):
    registernumber=models.CharField(max_length=200,null=True)
    nameofstudent=models.CharField(max_length=200,null=True)
    attendance=models.CharField(max_length=200,null=True)
    assignment=models.CharField(max_length=200,null=True)
    seminar=models.CharField(max_length=200,null=True)
    test1=models.CharField(max_length=200,null=True)
    test2=models.CharField(max_length=200,null=True)
    total=models.CharField(max_length=200,null=True)
class PROBLEM_SOLVING(models.Model):
    registernumber=models.CharField(max_length=200,null=True)
    nameofstudent=models.CharField(max_length=200,null=True)
    attendance=models.CharField(max_length=200,null=True)
    assignment=models.CharField(max_length=200,null=True)
    seminar=models.CharField(max_length=200,null=True)
    test1=models.CharField(max_length=200,null=True)
    test2=models.CharField(max_length=200,null=True)
    total=models.CharField(max_length=200,null=True)
class tableinfo12(models.Model):
    registernumber=models.CharField(max_length=200,null=True)
    nameofstudent=models.CharField(max_length=200,null=True)
    attendance=models.CharField(max_length=200,null=True)
    assignment=models.CharField(max_length=200,null=True)
    seminar=models.CharField(max_length=200,null=True)
    test1=models.CharField(max_length=200,null=True)
    test2=models.CharField(max_length=200,null=True)
    total=models.CharField(max_length=200,null=True)
class tableinfo13(models.Model):
    registernumber=models.CharField(max_length=200,null=True)
    nameofstudent=models.CharField(max_length=200,null=True)
    attendance=models.CharField(max_length=200,null=True)
    assignment=models.CharField(max_length=200,null=True)
    seminar=models.CharField(max_length=200,null=True)
    test1=models.CharField(max_length=200,null=True)
    test2=models.CharField(max_length=200,null=True)
    total=models.CharField(max_length=200,null=True)
class tableinfo14(models.Model):
    registernumber=models.CharField(max_length=200,null=True)
    nameofstudent=models.CharField(max_length=200,null=True)
    attendance=models.CharField(max_length=200,null=True)
    assignment=models.CharField(max_length=200,null=True)
    seminar=models.CharField(max_length=200,null=True)
    test1=models.CharField(max_length=200,null=True)
    test2=models.CharField(max_length=200,null=True)
    total=models.CharField(max_length=200,null=True)
class tableinfo15(models.Model):
    registernumber=models.CharField(max_length=200,null=True)
    nameofstudent=models.CharField(max_length=200,null=True)
    attendance=models.CharField(max_length=200,null=True)
    assignment=models.CharField(max_length=200,null=True)
    seminar=models.CharField(max_length=200,null=True)
    test1=models.CharField(max_length=200,null=True)
    test2=models.CharField(max_length=200,null=True)
    total=models.CharField(max_length=200,null=True)
class tableinfo16(models.Model):
    registernumber=models.CharField(max_length=200,null=True)
    nameofstudent=models.CharField(max_length=200,null=True)
    attendance=models.CharField(max_length=200,null=True)
    assignment=models.CharField(max_length=200,null=True)
    seminar=models.CharField(max_length=200,null=True)
    test1=models.CharField(max_length=200,null=True)
    test2=models.CharField(max_length=200,null=True)
    total=models.CharField(max_length=200,null=True)
class tableinfo17(models.Model):
    registernumber=models.CharField(max_length=200,null=True)
    nameofstudent=models.CharField(max_length=200,null=True)
    attendance=models.CharField(max_length=200,null=True)
    assignment=models.CharField(max_length=200,null=True)
    seminar=models.CharField(max_length=200,null=True)
    test1=models.CharField(max_length=200,null=True)
    test2=models.CharField(max_length=200,null=True)
    total=models.CharField(max_length=200,null=True)
class tableinfo18(models.Model):
    registernumber=models.CharField(max_length=200,null=True)
    nameofstudent=models.CharField(max_length=200,null=True)
    attendance=models.CharField(max_length=200,null=True)
    assignment=models.CharField(max_length=200,null=True)
    seminar=models.CharField(max_length=200,null=True)
    test1=models.CharField(max_length=200,null=True)
    test2=models.CharField(max_length=200,null=True)
    total=models.CharField(max_length=200,null=True)
class tableinfo19(models.Model):
    registernumber=models.CharField(max_length=200,null=True)
    nameofstudent=models.CharField(max_length=200,null=True)
    attendance=models.CharField(max_length=200,null=True)
    assignment=models.CharField(max_length=200,null=True)
    seminar=models.CharField(max_length=200,null=True)
    test1=models.CharField(max_length=200,null=True)
    test2=models.CharField(max_length=200,null=True)
    total=models.CharField(max_length=200,null=True)
class tableinfo20(models.Model):
    registernumber=models.CharField(max_length=200,null=True)
    nameofstudent=models.CharField(max_length=200,null=True)
    attendance=models.CharField(max_length=200,null=True)
    assignment=models.CharField(max_length=200,null=True)
    seminar=models.CharField(max_length=200,null=True)
    test1=models.CharField(max_length=200,null=True)
    test2=models.CharField(max_length=200,null=True)
    total=models.CharField(max_length=200,null=True)
class tableinfo21(models.Model):
    registernumber=models.CharField(max_length=200,null=True)
    nameofstudent=models.CharField(max_length=200,null=True)
    attendance=models.CharField(max_length=200,null=True)
    assignment=models.CharField(max_length=200,null=True)
    seminar=models.CharField(max_length=200,null=True)
    test1=models.CharField(max_length=200,null=True)
    test2=models.CharField(max_length=200,null=True)
    total=models.CharField(max_length=200,null=True)
class tableinfo22(models.Model):
    registernumber=models.CharField(max_length=200,null=True)
    nameofstudent=models.CharField(max_length=200,null=True)
    attendance=models.CharField(max_length=200,null=True)
    assignment=models.CharField(max_length=200,null=True)
    seminar=models.CharField(max_length=200,null=True)
    test1=models.CharField(max_length=200,null=True)
    test2=models.CharField(max_length=200,null=True)
    total=models.CharField(max_length=200,null=True)
class tableinfo23(models.Model):
    registernumber=models.CharField(max_length=200,null=True)
    nameofstudent=models.CharField(max_length=200,null=True)
    attendance=models.CharField(max_length=200,null=True)
    assignment=models.CharField(max_length=200,null=True)
    seminar=models.CharField(max_length=200,null=True)
    test1=models.CharField(max_length=200,null=True)
    test2=models.CharField(max_length=200,null=True)
    total=models.CharField(max_length=200,null=True)
class tableinfo24(models.Model):
    registernumber=models.CharField(max_length=200,null=True)
    nameofstudent=models.CharField(max_length=200,null=True)
    attendance=models.CharField(max_length=200,null=True)
    assignment=models.CharField(max_length=200,null=True)
    seminar=models.CharField(max_length=200,null=True)
    test1=models.CharField(max_length=200,null=True)
    test2=models.CharField(max_length=200,null=True)
    total=models.CharField(max_length=200,null=True)
class tableinfo25(models.Model):
    registernumber=models.CharField(max_length=200,null=True)
    nameofstudent=models.CharField(max_length=200,null=True)
    attendance=models.CharField(max_length=200,null=True)
    assignment=models.CharField(max_length=200,null=True)
    seminar=models.CharField(max_length=200,null=True)
    test1=models.CharField(max_length=200,null=True)
    test2=models.CharField(max_length=200,null=True)
    total=models.CharField(max_length=200,null=True)
class tableinfo26(models.Model):
    registernumber=models.CharField(max_length=200,null=True)
    nameofstudent=models.CharField(max_length=200,null=True)
    attendance=models.CharField(max_length=200,null=True)
    assignment=models.CharField(max_length=200,null=True)
    seminar=models.CharField(max_length=200,null=True)
    test1=models.CharField(max_length=200,null=True)
    test2=models.CharField(max_length=200,null=True)
    total=models.CharField(max_length=200,null=True)
class tableinfo27(models.Model):
    registernumber=models.CharField(max_length=200,null=True)
    nameofstudent=models.CharField(max_length=200,null=True)
    attendance=models.CharField(max_length=200,null=True)
    assignment=models.CharField(max_length=200,null=True)
    seminar=models.CharField(max_length=200,null=True)
    test1=models.CharField(max_length=200,null=True)
    test2=models.CharField(max_length=200,null=True)
    total=models.CharField(max_length=200,null=True)
class tableinfo28(models.Model):
    registernumber=models.CharField(max_length=200,null=True)
    nameofstudent=models.CharField(max_length=200,null=True)
    attendance=models.CharField(max_length=200,null=True)
    assignment=models.CharField(max_length=200,null=True)
    seminar=models.CharField(max_length=200,null=True)
    test1=models.CharField(max_length=200,null=True)
    test2=models.CharField(max_length=200,null=True)
    total=models.CharField(max_length=200,null=True)
class tableinfo29(models.Model):
    registernumber=models.CharField(max_length=200,null=True)
    nameofstudent=models.CharField(max_length=200,null=True)
    attendance=models.CharField(max_length=200,null=True)
    assignment=models.CharField(max_length=200,null=True)
    seminar=models.CharField(max_length=200,null=True)
    test1=models.CharField(max_length=200,null=True)
    test2=models.CharField(max_length=200,null=True)
    total=models.CharField(max_length=200,null=True)
class tableinfo30(models.Model):
    registernumber=models.CharField(max_length=200,null=True)
    nameofstudent=models.CharField(max_length=200,null=True)
    attendance=models.CharField(max_length=200,null=True)
    assignment=models.CharField(max_length=200,null=True)
    seminar=models.CharField(max_length=200,null=True)
    test1=models.CharField(max_length=200,null=True)
    test2=models.CharField(max_length=200,null=True)
    total=models.CharField(max_length=200,null=True)
class tableinfo31(models.Model):
    registernumber=models.CharField(max_length=200,null=True)
    nameofstudent=models.CharField(max_length=200,null=True)
    attendance=models.CharField(max_length=200,null=True)
    assignment=models.CharField(max_length=200,null=True)
    seminar=models.CharField(max_length=200,null=True)
    test1=models.CharField(max_length=200,null=True)
    test2=models.CharField(max_length=200,null=True)
    total=models.CharField(max_length=200,null=True)
class tableinfo32(models.Model):
    registernumber=models.CharField(max_length=200,null=True)
    nameofstudent=models.CharField(max_length=200,null=True)
    attendance=models.CharField(max_length=200,null=True)
    assignment=models.CharField(max_length=200,null=True)
    seminar=models.CharField(max_length=200,null=True)
    test1=models.CharField(max_length=200,null=True)
    test2=models.CharField(max_length=200,null=True)
    total=models.CharField(max_length=200,null=True)
class tableinfo33(models.Model):
    registernumber=models.CharField(max_length=200,null=True)
    nameofstudent=models.CharField(max_length=200,null=True)
    attendance=models.CharField(max_length=200,null=True)
    assignment=models.CharField(max_length=200,null=True)
    seminar=models.CharField(max_length=200,null=True)
    test1=models.CharField(max_length=200,null=True)
    test2=models.CharField(max_length=200,null=True)
    total=models.CharField(max_length=200,null=True)
class tableinfo34(models.Model):
    registernumber=models.CharField(max_length=200,null=True)
    nameofstudent=models.CharField(max_length=200,null=True)
    attendance=models.CharField(max_length=200,null=True)
    assignment=models.CharField(max_length=200,null=True)
    seminar=models.CharField(max_length=200,null=True)
    test1=models.CharField(max_length=200,null=True)
    test2=models.CharField(max_length=200,null=True)
    total=models.CharField(max_length=200,null=True)
class tableinfo35(models.Model):
    registernumber=models.CharField(max_length=200,null=True)
    nameofstudent=models.CharField(max_length=200,null=True)
    attendance=models.CharField(max_length=200,null=True)
    assignment=models.CharField(max_length=200,null=True)
    seminar=models.CharField(max_length=200,null=True)
    test1=models.CharField(max_length=200,null=True)
    test2=models.CharField(max_length=200,null=True)
    total=models.CharField(max_length=200,null=True)
class tableinfo36(models.Model):
    registernumber=models.CharField(max_length=200,null=True)
    nameofstudent=models.CharField(max_length=200,null=True)
    attendance=models.CharField(max_length=200,null=True)
    assignment=models.CharField(max_length=200,null=True)
    seminar=models.CharField(max_length=200,null=True)
    test1=models.CharField(max_length=200,null=True)
    test2=models.CharField(max_length=200,null=True)
    total=models.CharField(max_length=200,null=True)
class tableinfo37(models.Model):
    registernumber=models.CharField(max_length=200,null=True)
    nameofstudent=models.CharField(max_length=200,null=True)
    attendance=models.CharField(max_length=200,null=True)
    assignment=models.CharField(max_length=200,null=True)
    seminar=models.CharField(max_length=200,null=True)
    test1=models.CharField(max_length=200,null=True)
    test2=models.CharField(max_length=200,null=True)
    total=models.CharField(max_length=200,null=True)
class tableinfo38(models.Model):
    registernumber=models.CharField(max_length=200,null=True)
    nameofstudent=models.CharField(max_length=200,null=True)
    attendance=models.CharField(max_length=200,null=True)
    assignment=models.CharField(max_length=200,null=True)
    seminar=models.CharField(max_length=200,null=True)
    test1=models.CharField(max_length=200,null=True)
    test2=models.CharField(max_length=200,null=True)
    total=models.CharField(max_length=200,null=True)
class tableinfo39(models.Model):
    registernumber=models.CharField(max_length=200,null=True)
    nameofstudent=models.CharField(max_length=200,null=True)
    attendance=models.CharField(max_length=200,null=True)
    assignment=models.CharField(max_length=200,null=True)
    seminar=models.CharField(max_length=200,null=True)
    test1=models.CharField(max_length=200,null=True)
    test2=models.CharField(max_length=200,null=True)
    total=models.CharField(max_length=200,null=True)
class tableinfo40(models.Model):
    registernumber=models.CharField(max_length=200,null=True)
    nameofstudent=models.CharField(max_length=200,null=True)
    attendance=models.CharField(max_length=200,null=True)
    assignment=models.CharField(max_length=200,null=True)
    seminar=models.CharField(max_length=200,null=True)
    test1=models.CharField(max_length=200,null=True)
    test2=models.CharField(max_length=200,null=True)
    total=models.CharField(max_length=200,null=True)
class tableinfo41(models.Model):
    registernumber=models.CharField(max_length=200,null=True)
    nameofstudent=models.CharField(max_length=200,null=True)
    attendance=models.CharField(max_length=200,null=True)
    assignment=models.CharField(max_length=200,null=True)
    seminar=models.CharField(max_length=200,null=True)
    test1=models.CharField(max_length=200,null=True)
    test2=models.CharField(max_length=200,null=True)
    total=models.CharField(max_length=200,null=True)
class tableinfo42(models.Model):
    registernumber=models.CharField(max_length=200,null=True)
    nameofstudent=models.CharField(max_length=200,null=True)
    attendance=models.CharField(max_length=200,null=True)
    assignment=models.CharField(max_length=200,null=True)
    seminar=models.CharField(max_length=200,null=True)
    test1=models.CharField(max_length=200,null=True)
    test2=models.CharField(max_length=200,null=True)
    total=models.CharField(max_length=200,null=True)
class tableinfo43(models.Model):
    registernumber=models.CharField(max_length=200,null=True)
    nameofstudent=models.CharField(max_length=200,null=True)
    attendance=models.CharField(max_length=200,null=True)
    assignment=models.CharField(max_length=200,null=True)
    seminar=models.CharField(max_length=200,null=True)
    test1=models.CharField(max_length=200,null=True)
    test2=models.CharField(max_length=200,null=True)
    total=models.CharField(max_length=200,null=True)
class tableinfo44(models.Model):
    registernumber=models.CharField(max_length=200,null=True)
    nameofstudent=models.CharField(max_length=200,null=True)
    attendance=models.CharField(max_length=200,null=True)
    assignment=models.CharField(max_length=200,null=True)
    seminar=models.CharField(max_length=200,null=True)
    test1=models.CharField(max_length=200,null=True)
    test2=models.CharField(max_length=200,null=True)
    total=models.CharField(max_length=200,null=True)
class tableinfo45(models.Model):
    registernumber=models.CharField(max_length=200,null=True)
    nameofstudent=models.CharField(max_length=200,null=True)
    attendance=models.CharField(max_length=200,null=True)
    assignment=models.CharField(max_length=200,null=True)
    seminar=models.CharField(max_length=200,null=True)
    test1=models.CharField(max_length=200,null=True)
    test2=models.CharField(max_length=200,null=True)
    total=models.CharField(max_length=200,null=True)
class tableinfo46(models.Model):
    registernumber=models.CharField(max_length=200,null=True)
    nameofstudent=models.CharField(max_length=200,null=True)
    attendance=models.CharField(max_length=200,null=True)
    assignment=models.CharField(max_length=200,null=True)
    seminar=models.CharField(max_length=200,null=True)
    test1=models.CharField(max_length=200,null=True)
    test2=models.CharField(max_length=200,null=True)
    total=models.CharField(max_length=200,null=True)
class tableinfo47(models.Model):
    registernumber=models.CharField(max_length=200,null=True)
    nameofstudent=models.CharField(max_length=200,null=True)
    attendance=models.CharField(max_length=200,null=True)
    assignment=models.CharField(max_length=200,null=True)
    seminar=models.CharField(max_length=200,null=True)
    test1=models.CharField(max_length=200,null=True)
    test2=models.CharField(max_length=200,null=True)
    total=models.CharField(max_length=200,null=True)
class tableinfo48(models.Model):
    registernumber=models.CharField(max_length=200,null=True)
    nameofstudent=models.CharField(max_length=200,null=True)
    attendance=models.CharField(max_length=200,null=True)
    assignment=models.CharField(max_length=200,null=True)
    seminar=models.CharField(max_length=200,null=True)
    test1=models.CharField(max_length=200,null=True)
    test2=models.CharField(max_length=200,null=True)
    total=models.CharField(max_length=200,null=True)
class tableinfo49(models.Model):
    registernumber=models.CharField(max_length=200,null=True)
    nameofstudent=models.CharField(max_length=200,null=True)
    attendance=models.CharField(max_length=200,null=True)
    assignment=models.CharField(max_length=200,null=True)
    seminar=models.CharField(max_length=200,null=True)
    test1=models.CharField(max_length=200,null=True)
    test2=models.CharField(max_length=200,null=True)
    total=models.CharField(max_length=200,null=True)
class tableinfo50(models.Model):
    registernumber=models.CharField(max_length=200,null=True)
    nameofstudent=models.CharField(max_length=200,null=True)
    attendance=models.CharField(max_length=200,null=True)
    assignment=models.CharField(max_length=200,null=True)
    seminar=models.CharField(max_length=200,null=True)
    test1=models.CharField(max_length=200,null=True)
    test2=models.CharField(max_length=200,null=True)
    total=models.CharField(max_length=200,null=True)
class tableinfo51(models.Model):
    registernumber=models.CharField(max_length=200,null=True)
    nameofstudent=models.CharField(max_length=200,null=True)
    attendance=models.CharField(max_length=200,null=True)
    assignment=models.CharField(max_length=200,null=True)
    seminar=models.CharField(max_length=200,null=True)
    test1=models.CharField(max_length=200,null=True)
    test2=models.CharField(max_length=200,null=True)
    total=models.CharField(max_length=200,null=True)
class tableinfo52(models.Model):
    registernumber=models.CharField(max_length=200,null=True)
    nameofstudent=models.CharField(max_length=200,null=True)
    attendance=models.CharField(max_length=200,null=True)
    assignment=models.CharField(max_length=200,null=True)
    seminar=models.CharField(max_length=200,null=True)
    test1=models.CharField(max_length=200,null=True)
    test2=models.CharField(max_length=200,null=True)
    total=models.CharField(max_length=200,null=True)
class tableinfo53(models.Model):
    registernumber=models.CharField(max_length=200,null=True)
    nameofstudent=models.CharField(max_length=200,null=True)
    attendance=models.CharField(max_length=200,null=True)
    assignment=models.CharField(max_length=200,null=True)
    seminar=models.CharField(max_length=200,null=True)
    test1=models.CharField(max_length=200,null=True)
    test2=models.CharField(max_length=200,null=True)
    total=models.CharField(max_length=200,null=True)
class tableinfo54(models.Model):
    registernumber=models.CharField(max_length=200,null=True)
    nameofstudent=models.CharField(max_length=200,null=True)
    attendance=models.CharField(max_length=200,null=True)
    assignment=models.CharField(max_length=200,null=True)
    seminar=models.CharField(max_length=200,null=True)
    test1=models.CharField(max_length=200,null=True)
    test2=models.CharField(max_length=200,null=True)
    total=models.CharField(max_length=200,null=True)
class tableinfo55(models.Model):
    registernumber=models.CharField(max_length=200,null=True)
    nameofstudent=models.CharField(max_length=200,null=True)
    attendance=models.CharField(max_length=200,null=True)
    assignment=models.CharField(max_length=200,null=True)
    seminar=models.CharField(max_length=200,null=True)
    test1=models.CharField(max_length=200,null=True)
    test2=models.CharField(max_length=200,null=True)
    total=models.CharField(max_length=200,null=True)
class tableinfo56(models.Model):
    registernumber=models.CharField(max_length=200,null=True)
    nameofstudent=models.CharField(max_length=200,null=True)
    attendance=models.CharField(max_length=200,null=True)
    assignment=models.CharField(max_length=200,null=True)
    seminar=models.CharField(max_length=200,null=True)
    test1=models.CharField(max_length=200,null=True)
    test2=models.CharField(max_length=200,null=True)
    total=models.CharField(max_length=200,null=True)
class tableinfo57(models.Model):
    registernumber=models.CharField(max_length=200,null=True)
    nameofstudent=models.CharField(max_length=200,null=True)
    attendance=models.CharField(max_length=200,null=True)
    assignment=models.CharField(max_length=200,null=True)
    seminar=models.CharField(max_length=200,null=True)
    test1=models.CharField(max_length=200,null=True)
    test2=models.CharField(max_length=200,null=True)
    total=models.CharField(max_length=200,null=True)
class tableinfo58(models.Model):
    registernumber=models.CharField(max_length=200,null=True)
    nameofstudent=models.CharField(max_length=200,null=True)
    attendance=models.CharField(max_length=200,null=True)
    assignment=models.CharField(max_length=200,null=True)
    seminar=models.CharField(max_length=200,null=True)
    test1=models.CharField(max_length=200,null=True)
    test2=models.CharField(max_length=200,null=True)
    total=models.CharField(max_length=200,null=True)
class tableinfo59(models.Model):
    registernumber=models.CharField(max_length=200,null=True)
    nameofstudent=models.CharField(max_length=200,null=True)
    attendance=models.CharField(max_length=200,null=True)
    assignment=models.CharField(max_length=200,null=True)
    seminar=models.CharField(max_length=200,null=True)
    test1=models.CharField(max_length=200,null=True)
    test2=models.CharField(max_length=200,null=True)
    total=models.CharField(max_length=200,null=True)
class tableinfo60(models.Model):
    registernumber=models.CharField(max_length=200,null=True)
    nameofstudent=models.CharField(max_length=200,null=True)
    attendance=models.CharField(max_length=200,null=True)
    assignment=models.CharField(max_length=200,null=True)
    seminar=models.CharField(max_length=200,null=True)
    test1=models.CharField(max_length=200,null=True)
    test2=models.CharField(max_length=200,null=True)
    total=models.CharField(max_length=200,null=True)
class tableinfo61(models.Model):
    registernumber=models.CharField(max_length=200,null=True)
    nameofstudent=models.CharField(max_length=200,null=True)
    attendance=models.CharField(max_length=200,null=True)
    assignment=models.CharField(max_length=200,null=True)
    seminar=models.CharField(max_length=200,null=True)
    test1=models.CharField(max_length=200,null=True)
    test2=models.CharField(max_length=200,null=True)
    total=models.CharField(max_length=200,null=True)
class tableinfo62(models.Model):
    registernumber=models.CharField(max_length=200,null=True)
    nameofstudent=models.CharField(max_length=200,null=True)
    attendance=models.CharField(max_length=200,null=True)
    assignment=models.CharField(max_length=200,null=True)
    seminar=models.CharField(max_length=200,null=True)
    test1=models.CharField(max_length=200,null=True)
    test2=models.CharField(max_length=200,null=True)
    total=models.CharField(max_length=200,null=True)
class tableinfo63(models.Model):
    registernumber=models.CharField(max_length=200,null=True)
    nameofstudent=models.CharField(max_length=200,null=True)
    attendance=models.CharField(max_length=200,null=True)
    assignment=models.CharField(max_length=200,null=True)
    seminar=models.CharField(max_length=200,null=True)
    test1=models.CharField(max_length=200,null=True)
    test2=models.CharField(max_length=200,null=True)
    total=models.CharField(max_length=200,null=True)
class tableinfo64(models.Model):
    registernumber=models.CharField(max_length=200,null=True)
    nameofstudent=models.CharField(max_length=200,null=True)
    attendance=models.CharField(max_length=200,null=True)
    assignment=models.CharField(max_length=200,null=True)
    seminar=models.CharField(max_length=200,null=True)
    test1=models.CharField(max_length=200,null=True)
    test2=models.CharField(max_length=200,null=True)
    total=models.CharField(max_length=200,null=True)
class tableinfo65(models.Model):
    registernumber=models.CharField(max_length=200,null=True)
    nameofstudent=models.CharField(max_length=200,null=True)
    attendance=models.CharField(max_length=200,null=True)
    assignment=models.CharField(max_length=200,null=True)
    seminar=models.CharField(max_length=200,null=True)
    test1=models.CharField(max_length=200,null=True)
    test2=models.CharField(max_length=200,null=True)
    total=models.CharField(max_length=200,null=True)
class tableinfo66(models.Model):
    registernumber=models.CharField(max_length=200,null=True)
    nameofstudent=models.CharField(max_length=200,null=True)
    attendance=models.CharField(max_length=200,null=True)
    assignment=models.CharField(max_length=200,null=True)
    seminar=models.CharField(max_length=200,null=True)
    test1=models.CharField(max_length=200,null=True)
    test2=models.CharField(max_length=200,null=True)
    total=models.CharField(max_length=200,null=True)
class tableinfo67(models.Model):
    registernumber=models.CharField(max_length=200,null=True)
    nameofstudent=models.CharField(max_length=200,null=True)
    attendance=models.CharField(max_length=200,null=True)
    assignment=models.CharField(max_length=200,null=True)
    seminar=models.CharField(max_length=200,null=True)
    test1=models.CharField(max_length=200,null=True)
    test2=models.CharField(max_length=200,null=True)
    total=models.CharField(max_length=200,null=True)
class tableinfo68(models.Model):
    registernumber=models.CharField(max_length=200,null=True)
    nameofstudent=models.CharField(max_length=200,null=True)
    attendance=models.CharField(max_length=200,null=True)
    assignment=models.CharField(max_length=200,null=True)
    seminar=models.CharField(max_length=200,null=True)
    test1=models.CharField(max_length=200,null=True)
    test2=models.CharField(max_length=200,null=True)
    total=models.CharField(max_length=200,null=True)
class tableinfo69(models.Model):
    registernumber=models.CharField(max_length=200,null=True)
    nameofstudent=models.CharField(max_length=200,null=True)
    attendance=models.CharField(max_length=200,null=True)
    assignment=models.CharField(max_length=200,null=True)
    seminar=models.CharField(max_length=200,null=True)
    test1=models.CharField(max_length=200,null=True)
    test2=models.CharField(max_length=200,null=True)
    total=models.CharField(max_length=200,null=True)
class tableinfo70(models.Model):
    registernumber=models.CharField(max_length=200,null=True)
    nameofstudent=models.CharField(max_length=200,null=True)
    attendance=models.CharField(max_length=200,null=True)
    assignment=models.CharField(max_length=200,null=True)
    seminar=models.CharField(max_length=200,null=True)
    test1=models.CharField(max_length=200,null=True)
    test2=models.CharField(max_length=200,null=True)
    total=models.CharField(max_length=200,null=True)



