# Generated by Django 4.1.3 on 2022-12-04 16:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("polls", "0003_alter_depinformation_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="tableinfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("registernumber", models.CharField(max_length=200, null=True)),
                ("nameofstudent", models.CharField(max_length=200, null=True)),
                ("attendance", models.CharField(max_length=200, null=True)),
                ("assignment", models.CharField(max_length=200, null=True)),
                ("seminar", models.CharField(max_length=200, null=True)),
                ("test1", models.IntegerField(max_length=200, null=True)),
                ("test2", models.IntegerField(max_length=200, null=True)),
                ("total", models.IntegerField(max_length=200, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
