# Generated by Django 4.1.3 on 2022-12-04 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0005_rename_nameofstudent_tableinfo_department_and_more"),
    ]

    operations = [
        migrations.RenameField(model_name="tableinfo", old_name="test1", new_name="a",),
        migrations.RenameField(model_name="tableinfo", old_name="test2", new_name="b",),
        migrations.AddField(
            model_name="tableinfo",
            name="c",
            field=models.IntegerField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="tableinfo",
            name="d",
            field=models.IntegerField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="tableinfo",
            name="e",
            field=models.IntegerField(max_length=200, null=True),
        ),
    ]
