# Generated by Django 4.1.3 on 2022-12-09 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0007_e_d_c_b_a"),
    ]

    operations = [
        migrations.AddField(
            model_name="a",
            name="sem",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="b",
            name="sem",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="c",
            name="sem",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="d",
            name="sem",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="e",
            name="sem",
            field=models.CharField(max_length=200, null=True),
        ),
    ]
