# Generated by Django 4.1.3 on 2022-12-18 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0012_sem1_sem2_sem3_sem4_sem5_sem6_remove_b_user_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="sem1",
            name="branch",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="sem2",
            name="branch",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="sem3",
            name="branch",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="sem4",
            name="branch",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="sem5",
            name="branch",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="sem6",
            name="branch",
            field=models.CharField(max_length=200, null=True),
        ),
    ]
